#!/usr/bin/env python3
"""Generate the SSB Hilbert-transformer coefficients (src/hilbert_coefs.vh).

Type-III (odd length, antisymmetric) FIR approximating the ideal Hilbert
transformer h[k] = 2/(pi*k) for odd k (0 for even k), Kaiser-windowed and
quantised to Q15. The design is fixed by platform.json (ssb.hilbert_taps,
ssb.audio_rate_hz); the script also prints the magnitude error over the voice
band so a tap-count change can be judged.

    scripts/hilbert_generator.py            # regenerate src/hilbert_coefs.vh
    scripts/hilbert_generator.py --report   # only print the response table
"""

import argparse
import cmath
import math
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
import platform_config as pc  # noqa: E402

KAISER_BETA = 6.0


def _i0(x: float) -> float:
    """Modified Bessel function of the first kind, order 0 (series)."""
    s, t, k = 1.0, 1.0, 1
    while t > 1e-12 * s:
        t *= (x / (2 * k)) ** 2
        s += t
        k += 1
    return s


def kaiser(n: int, beta: float) -> list[float]:
    m = n - 1
    return [_i0(beta * math.sqrt(1 - ((2 * i - m) / m) ** 2)) / _i0(beta) for i in range(n)]


def hilbert_taps(n: int, beta: float = KAISER_BETA) -> list[float]:
    if n % 2 == 0:
        raise ValueError("tap count must be odd")
    c = (n - 1) // 2
    w = kaiser(n, beta)
    return [0.0 if (i - c) % 2 == 0 else (2 / (math.pi * (i - c))) * w[i] for i in range(n)]


def quantize(h: list[float]) -> list[int]:
    q = [max(-32768, min(32767, int(round(v * 32768)))) for v in h]
    return q


def response(hq: list[int], f: float, fs: float) -> complex:
    w = 2 * math.pi * f / fs
    return sum(v / 32768 * cmath.exp(-1j * w * i) for i, v in enumerate(hq))


def report(hq: list[int], fs: float) -> None:
    c = (len(hq) - 1) // 2
    print(f"{len(hq)} taps, group delay {c} samples ({1000 * c / fs:.2f} ms) at {fs:.0f} S/s")
    print("   f [Hz]   |H| [dB]   phase err [deg]")
    worst = 0.0
    for f in (200, 300, 400, 500, 700, 1000, 1500, 2000, 2500, 3000, 3400, 4000, 5000):
        h = response(hq, f, fs) * cmath.exp(1j * 2 * math.pi * f / fs * c)   # remove the delay
        mag = 20 * math.log10(abs(h))
        ph = math.degrees(cmath.phase(h)) + 90.0
        print(f"  {f:6.0f}  {mag:8.3f}  {ph:10.3f}")
        if 300 <= f <= 3400:
            worst = max(worst, abs(mag))
    print(f"worst |H| deviation in 300..3400 Hz: {worst:.3f} dB")


def render(hq: list[int]) -> str:
    lines = [
        "// Auto-generated by scripts/hilbert_generator.py -- do not edit.",
        f"// {len(hq)}-tap type-III Hilbert transformer, Kaiser beta={KAISER_BETA}, Q15,",
        f"// designed for {pc.SSB_AUDIO_RATE_HZ} S/s. Included inside `initial begin ... end`.",
    ]
    for i, v in enumerate(hq):
        lines.append(f"hilbert_rom['h{i:02X}] = 16'h{v & 0xFFFF:04X};")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--taps", type=int, default=pc.SSB_HILBERT_TAPS)
    ap.add_argument("--beta", type=float, default=KAISER_BETA)
    ap.add_argument("--report", action="store_true", help="print the response table only")
    ap.add_argument("-o", "--output", default=os.path.join(ROOT, "src", "hilbert_coefs.vh"))
    args = ap.parse_args()
    hq = quantize(hilbert_taps(args.taps, args.beta))
    report(hq, pc.SSB_AUDIO_RATE_HZ)
    if not args.report:
        with open(args.output, "w") as f:
            f.write(render(hq))
        print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
