#!/usr/bin/env python3
"""Generate the DDS sine ROM initialiser (src/sine_lut_init.vh).

Emits one full period of sin() as signed two's-complement DAC-scale values
(full scale = +-(2^(bits-1) - 1)), one `sine_rom[i] = ...;` line per entry, for
inclusion inside an `initial begin ... end` block in dds_channel.sv.

Defaults come from platform.json (dac.bits / dac.sine_lut_depth) via
platform_config.py so the ROM always matches the DAC width the gateware uses.

    scripts/sine_lut_generator.py                  # regenerate src/sine_lut_init.vh
    scripts/sine_lut_generator.py --depth 256 -o /tmp/x.vh
"""

import argparse
import math
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
import platform_config as pc  # noqa: E402


def sine_table(depth: int, bits: int) -> list[int]:
    """First quadrant of a `depth`-point full-wave sine: k = 0 .. depth/4-1.

    dds_channel.sv folds the other three quadrants by mirroring the index and
    negating, and inserts the exact +-full-scale peak at depth/4 and 3*depth/4
    (the one value a mirrored index cannot reach), so the result is bit-identical
    to a full table of round(full * sin(2*pi*a/depth))."""
    full = (1 << (bits - 1)) - 1
    return [int(round(full * math.sin(2 * math.pi * i / depth))) for i in range(depth // 4)]


def to_twos(v: int, bits: int) -> int:
    return v & ((1 << bits) - 1)


def render(depth: int, bits: int) -> str:
    hexw = (bits + 3) // 4
    idxw = max(1, (max(depth // 4 - 1, 1).bit_length() + 3) // 4)
    lines = [
        "// Auto-generated by scripts/sine_lut_generator.py -- do not edit.",
        f"// First quadrant ({depth // 4} entries) of a {depth}-point {bits}-bit sine, "
        f"full scale +-{(1 << (bits - 1)) - 1};",
        "// dds_channel.sv folds the other quadrants. Included inside `initial begin ... end`.",
    ]
    for i, v in enumerate(sine_table(depth, bits)):
        lines.append(f"sine_rom['h{i:0{idxw}X}] = {bits}'h{to_twos(v, bits):0{hexw}X};")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--depth", type=int, default=pc.SINE_LUT_DEPTH, help="table entries (power of two)")
    ap.add_argument("--bits", type=int, default=pc.DAC_BITS, help="sample width in bits")
    ap.add_argument("-o", "--output", default=os.path.join(ROOT, "src", "sine_lut_init.vh"))
    args = ap.parse_args()
    if args.depth & (args.depth - 1):
        sys.exit("--depth must be a power of two")
    with open(args.output, "w") as f:
        f.write(render(args.depth, args.bits))
    print(f"wrote {args.output}: {args.depth // 4} x {args.bits}-bit (quarter of {args.depth})")


if __name__ == "__main__":
    main()
