`include "timescale.v"
`include "acm9767_defs.vh"
`include "platform_config.vh"   // generated by CMake from platform.json

`default_nettype wire

// Tang Nano 9K -> ACM9767 (AD9767 dual 14-bit DAC) controller.
//
// Two clock domains:
//   sys_clk (27 MHz crystal)  UART + Modbus RTU slave + register file (dac_regs)
//   dac_clk (rPLL, platform.json pll.*)  DDS channel(s), SSB baseband chain,
//                                        DAC output stage
// Crossings: the committed register snapshot (cdc_commit_sync), the audio
// sample FIFO (async_fifo), the underrun toggle and the PLL lock status.
//
// Host side: Modbus RTU over the FT2232H channel-B UART (/dev/ttyGowin),
// see scripts/acm9767_ctl.py and README.md for the register map.

module acm9767_top (
    input  wire        sys_clk,      // 27 MHz, pin 52
    input  wire        sys_rst_n,    // S1 button, pin 4 (active low)
    output wire        uart_tx,      // FPGA -> host, pin 17
    input  wire        uart_rx,      // host -> FPGA, pin 18
    output wire [5:0]  leds,         // on-board LEDs, active low
    output wire        da1_clk,      // AD9767 CLK1
    output wire        da1_wrt,      // AD9767 WRT1 (same edge as CLK1)
    output wire [13:0] da1_data      // AD9767 DB13..DB0 of port 1
`ifdef PLATFORM_DAC_CH2
    ,
    output wire        da2_clk,
    output wire        da2_wrt,
    output wire [13:0] da2_data
`endif
);

// ---------------------------------------------------------------- clocks/resets
wire sys_rst_n_s;
reset_sync sys_reset_sync (.clk(sys_clk), .async_rst_n(sys_rst_n), .rst_n(sys_rst_n_s));

wire dac_clk, pll_lock;
dac_pll pll (.clkin(sys_clk), .reset(~sys_rst_n), .clkout(dac_clk), .lock(pll_lock));

wire dac_rst_n;
reset_sync dac_reset_sync (.clk(dac_clk), .async_rst_n(sys_rst_n & pll_lock), .rst_n(dac_rst_n));

// PLL lock into the sys domain for STATUS / LED
reg pll_lock_s0, pll_lock_s1;
always @(posedge sys_clk or negedge sys_rst_n_s) begin
    if (!sys_rst_n_s) begin
        pll_lock_s0 <= `WRAP_SIM(#1) 1'b0;
        pll_lock_s1 <= `WRAP_SIM(#1) 1'b0;
    end else begin
        pll_lock_s0 <= `WRAP_SIM(#1) pll_lock;
        pll_lock_s1 <= `WRAP_SIM(#1) pll_lock_s0;
    end
end

// ---------------------------------------------------------------- UART + Modbus
wire [7:0] rx_data;
wire       rx_valid, rx_perr;
wire [7:0] tx_data;
wire       tx_start, tx_busy;

uart #(
    .CLK_FREQ (`PLATFORM_SYS_CLK_HZ),
    .BAUD     (`PLATFORM_UART_BAUD),
    .DATA_BITS(`PLATFORM_UART_DATA_BITS),
    .PARITY   (`PLATFORM_UART_PARITY),
    .STOP_BITS(`PLATFORM_UART_STOP_BITS)
) uart_inst (
    .clk(sys_clk), .reset_n(sys_rst_n_s),
    .tx_data(tx_data), .tx_start(tx_start), .tx_busy(tx_busy), .tx(uart_tx),
    .rx(uart_rx), .rx_data(rx_data), .rx_valid(rx_valid),
    .rx_parity_error(rx_perr), .rx_frame_error()
);

wire        be_req, be_we, be_ready;
wire [15:0] be_addr, be_wdata, be_rdata;

modbus_rtu_slave #(
    .CLK_FREQ        (`PLATFORM_SYS_CLK_HZ),
    .BAUD            (`PLATFORM_UART_BAUD),
    .SLAVE_ADDR      (`PLATFORM_MODBUS_DEVICE_ID),
    .REG_COUNT       (1),                              // external backend: no internal file
    .ADDR_LIMIT      (`PLATFORM_MODBUS_ADDR_LIMIT),
    .MAX_FRAME       (`PLATFORM_MODBUS_MAX_FRAME),
    .MAX_QTY         (`PLATFORM_MODBUS_MAX_READ_QTY),
    .EXTERNAL_BACKEND(1)
) modbus_inst (
    .clk(sys_clk), .reset_n(sys_rst_n_s),
    .rx_data(rx_data), .rx_valid(rx_valid), .rx_parity_error(rx_perr),
    .tx_data(tx_data), .tx_start(tx_start), .tx_busy(tx_busy),
    .reg_o(), .host_we(1'b0), .host_addr(8'h00), .host_wdata(16'h0000),
    .be_req(be_req), .be_we(be_we), .be_addr(be_addr), .be_wdata(be_wdata),
    .be_ready(be_ready), .be_rdata(be_rdata)
);

// ---------------------------------------------------------------- registers + CDC
wire [`COMMIT_WORD_W-1:0] commit_word, dds_word;
wire                      commit_pulse, commit_busy, cdc_busy, dds_load;
wire [`CTRL_WORD_W-1:0]   ctrl_committed;
wire                      fifo_wr, fifo_full, fifo_rd, fifo_empty, underrun_tog;
wire [15:0]               fifo_wdata, fifo_rdata;
wire [`PLATFORM_SSB_FIFO_LOG2:0] fifo_level;

dac_regs regs (
    .clk(sys_clk), .rst_n(sys_rst_n_s),
    .be_req(be_req), .be_we(be_we), .be_addr(be_addr), .be_wdata(be_wdata),
    .be_ready(be_ready), .be_rdata(be_rdata),
    .pll_lock(pll_lock_s1), .cdc_busy(cdc_busy),
    .fifo_wr(fifo_wr), .fifo_wdata(fifo_wdata), .fifo_level(fifo_level), .underrun_tog(underrun_tog),
    .commit_word(commit_word), .commit_pulse(commit_pulse), .commit_busy(commit_busy),
    .ctrl_committed(ctrl_committed)
);

// ---------------------------------------------------------------- audio FIFO + SSB baseband
async_fifo #(.WIDTH(16), .DEPTH_LOG2(`PLATFORM_SSB_FIFO_LOG2)) audio_fifo (
    .wclk(sys_clk), .wrst_n(sys_rst_n_s), .wr_en(fifo_wr), .wdata(fifo_wdata),
    .wfull(fifo_full), .wlevel(fifo_level),
    .rclk(dac_clk), .rrst_n(dac_rst_n), .rd_en(fifo_rd), .rdata(fifo_rdata), .rempty(fifo_empty)
);

wire signed [15:0] bb_i, bb_q;
ssb_baseband baseband (
    .clk(dac_clk), .rst_n(dac_rst_n),
    .fifo_rd(fifo_rd), .fifo_rdata(fifo_rdata), .fifo_empty(fifo_empty),
    .bb_i(bb_i), .bb_q(bb_q), .underrun_tog(underrun_tog)
);

cdc_commit_sync #(.WORD_WIDTH(`COMMIT_WORD_W)) commit_cdc (
    .s_clk(sys_clk), .s_rst_n(sys_rst_n_s),
    .s_commit(commit_pulse), .s_data(commit_word), .s_busy(cdc_busy),
    .r_clk(dac_clk), .r_rst_n(dac_rst_n),
    .r_data(dds_word), .r_load(dds_load)
);

// ---------------------------------------------------------------- DDS channels
// Channel 2 exists only when platform.json dac.channels == 2 (PLATFORM_DAC_CH2);
// its registers are still writable on a 1-channel build but drive nothing.
wire [`CTRL_WORD_W-1:0] ctrl = dds_word[`COMMIT_WORD_W-1 -: `CTRL_WORD_W];
wire [`CH_WORD_W-1:0]   ch1  = dds_word[`CH_WORD_W-1:0];
wire [13:0] code1;

dds_channel dds1 (
    .clk(dac_clk), .rst_n(dac_rst_n),
    .en(ctrl[`CTRL_CH1_EN]), .invert(ctrl[`CTRL_CH1_INVERT]),
    .ftw(`CH_FTW(ch1)), .phase_ofs(`CH_PHASE(ch1)), .amplitude(`CH_AMPLITUDE(ch1)),
    .offset(`CH_OFFSET(ch1)), .waveform(`CH_WAVEFORM(ch1)), .duty(`CH_DUTY(ch1)),
    .modparam(`CH_MODPARAM(ch1)), .bb_i(bb_i), .bb_q(bb_q),
    .dac_code(code1)
);
dac_output_stage out1 (
    .clk(dac_clk), .rst_n(dac_rst_n), .code(code1),
    .da_clk(da1_clk), .da_wrt(da1_wrt), .da_data(da1_data)
);

`ifdef PLATFORM_DAC_CH2
wire [`CH_WORD_W-1:0] ch2 = dds_word[2*`CH_WORD_W-1:`CH_WORD_W];
wire [13:0] code2;
dds_channel dds2 (
    .clk(dac_clk), .rst_n(dac_rst_n),
    .en(ctrl[`CTRL_CH2_EN]), .invert(ctrl[`CTRL_CH2_INVERT]),
    .ftw(`CH_FTW(ch2)), .phase_ofs(`CH_PHASE(ch2)), .amplitude(`CH_AMPLITUDE(ch2)),
    .offset(`CH_OFFSET(ch2)), .waveform(`CH_WAVEFORM(ch2)), .duty(`CH_DUTY(ch2)),
    .modparam(`CH_MODPARAM(ch2)), .bb_i(bb_i), .bb_q(bb_q),
    .dac_code(code2)
);
dac_output_stage out2 (
    .clk(dac_clk), .rst_n(dac_rst_n), .code(code2),
    .da_clk(da2_clk), .da_wrt(da2_wrt), .da_data(da2_data)
);
wire ch2_enabled = ctrl_committed[`CTRL_CH2_EN];
`else
wire ch2_enabled = 1'b0;
`endif

// ---------------------------------------------------------------- LEDs (active low)
// 0 PLL lock  1 ch1 enabled  2 ch2 enabled  3 UART activity  4 sys heartbeat  5 dac heartbeat
reg [21:0] uart_act;    // ~150 ms stretch at 27 MHz
always @(posedge sys_clk or negedge sys_rst_n_s) begin
    if (!sys_rst_n_s)  uart_act <= `WRAP_SIM(#1) 22'd0;
    else if (rx_valid) uart_act <= `WRAP_SIM(#1) {22{1'b1}};
    else if (|uart_act) uart_act <= `WRAP_SIM(#1) uart_act - 1'b1;
end

reg [24:0] hb_sys;
always @(posedge sys_clk or negedge sys_rst_n_s)
    if (!sys_rst_n_s) hb_sys <= `WRAP_SIM(#1) 25'd0;
    else              hb_sys <= `WRAP_SIM(#1) hb_sys + 1'b1;

reg [25:0] hb_dac;
always @(posedge dac_clk or negedge dac_rst_n)
    if (!dac_rst_n) hb_dac <= `WRAP_SIM(#1) 26'd0;
    else            hb_dac <= `WRAP_SIM(#1) hb_dac + 1'b1;

assign leds[0] = ~pll_lock_s1;
assign leds[1] = ~ctrl_committed[`CTRL_CH1_EN];
assign leds[2] = ~ch2_enabled;
assign leds[3] = ~(|uart_act);
assign leds[4] = ~hb_sys[24];
assign leds[5] = ~hb_dac[25];

endmodule
