`include "timescale.v"
`include "acm9767_defs.vh"
`include "platform_config.vh"

// One DDS (direct digital synthesis) channel producing straight-binary DAC
// codes for the AD9767 at one sample per clk.
//
//   phase_acc += ftw            f_out = ftw * f_clk / 2^32
//   ph = phase_acc[31:16] + phase_ofs
//   raw = waveform(ph)          signed 14-bit, full scale +-8191
//         SSB: bb_i*cos(ph) -/+ bb_q*sin(ph)  (USB: minus, LSB: plus)
//         AM : (1 + depth*bb_i) * cos(ph) / 2   depth = modparam / 65536
//         FM : phase_acc += ftw + bb_i*modparam*256/32768  (deviation at full-scale audio
//              = modparam*256 FTW units; NFM 5 kHz at 54 MHz = modparam 1553)
//   scaled = raw * (amplitude + 1) >> 16   (0xFFFF = unity gain)
//   sum = sat14(scaled + offset)
//   dac_code = en ? (sum + 8192) ^ {14{invert}} : 0x2000 (mid-scale = 0 V)
//
// The sine table stores only the first quadrant (PLATFORM_SINE_LUT_DEPTH/4
// entries of src/sine_lut_init.vh, generated by scripts/sine_lut_generator.py);
// the top LUT_ADDR_W phase bits select a full-wave point and the other three
// quadrants are folded by index mirroring / negation, bit-identical to a full
// table (4096 points -> phase-truncation spurs ~-72 dBc). sin and cos are two
// reads of the same quarter table (cos = phase + a quarter turn).
// Pipeline latency is 6-8 clocks depending on the waveform; irrelevant for a
// free-running generator.

module dds_channel #(
    // sine ROM address width from platform.json dac.sine_lut_depth (4096 -> 12 bits)
    parameter integer LUT_ADDR_W = $clog2(`PLATFORM_SINE_LUT_DEPTH)
) (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    input  wire        invert,
    input  wire [31:0] ftw,
    input  wire [15:0] phase_ofs,
    input  wire [15:0] amplitude,
    input  wire [15:0] offset,       // signed
    input  wire [3:0]  waveform,
    input  wire [15:0] duty,
    input  wire [15:0] modparam,
    // analytic baseband from ssb_baseband (Q15, DAC rate) for WAVE_SSB_*
    input  wire signed [15:0] bb_i,
    input  wire signed [15:0] bb_q,
    output reg  [13:0] dac_code
);

localparam integer LUT_DEPTH = 1 << LUT_ADDR_W;

// ---- quarter-wave sine ROM ----
localparam integer QW = LUT_ADDR_W - 2;          // quarter-table index width
reg [13:0] sine_rom [0:(1<<QW)-1];               // sin(2*pi*k/LUT_DEPTH), k = 0 .. LUT_DEPTH/4-1
initial begin
`include "sine_lut_init.vh"
end

// full-wave address a[LUT_ADDR_W-1:0]: a[MSB] = second half (negate),
// a[MSB-1] = mirrored quadrant (index LUT_DEPTH/4 - low; low == 0 is the exact peak)
function [QW-1:0] qidx(input [LUT_ADDR_W-1:0] a);
    begin
        qidx = a[LUT_ADDR_W-2] ? ({QW{1'b0}} - a[QW-1:0]) : a[QW-1:0];
    end
endfunction

// ---- baseband delayed two clocks: the quarter-wave ROM fold is two pipeline
// stages (peak mux, negate) deeper than a plain table read; this keeps the
// baseband/carrier alignment (bit-identical output to the un-folded design,
// two samples later) ----
reg signed [15:0] bb_i_d1, bb_q_d1, bb_i_d, bb_q_d;
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        bb_i_d1 <= `WRAP_SIM(#1) 16'sd0; bb_q_d1 <= `WRAP_SIM(#1) 16'sd0;
        bb_i_d  <= `WRAP_SIM(#1) 16'sd0; bb_q_d  <= `WRAP_SIM(#1) 16'sd0;
    end else begin
        bb_i_d1 <= `WRAP_SIM(#1) bb_i;   bb_q_d1 <= `WRAP_SIM(#1) bb_q;
        bb_i_d  <= `WRAP_SIM(#1) bb_i_d1; bb_q_d  <= `WRAP_SIM(#1) bb_q_d1;
    end
end

// ---- modulation product shared by AM and FM: bb_i (Q15) * modparam (unsigned 16) ----
reg signed [32:0] mod_prod;
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) mod_prod <= `WRAP_SIM(#1) 33'sd0;
    else        mod_prod <= `WRAP_SIM(#1) bb_i_d * $signed({1'b0, modparam});
end

// ---- stage 0: phase accumulator (+ FM deviation: mod_prod * 256 / 32768) ----
reg [31:0] phase_acc;
reg signed [25:0] fm_dev;
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) fm_dev <= `WRAP_SIM(#1) 26'sd0;
    else        fm_dev <= `WRAP_SIM(#1) (waveform == `WAVE_FM) ? mod_prod[32:7] : 26'sd0;
end
always @(posedge clk or negedge rst_n) begin
    if (!rst_n)  phase_acc <= `WRAP_SIM(#1) 32'd0;
    else if (en) phase_acc <= `WRAP_SIM(#1) phase_acc + ftw + {{6{fm_dev[25]}}, fm_dev};
    else         phase_acc <= `WRAP_SIM(#1) 32'd0;
end

// ---- stage 1: effective phase ----
reg [15:0] ph;
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) ph <= `WRAP_SIM(#1) 16'd0;
    else        ph <= `WRAP_SIM(#1) phase_acc[31:16] + phase_ofs;
end

// ---- stage 2: raw waveforms (all registered, same latency as the ROM read) ----
// 15-bit intermediates so the +-8192 offsets cannot overflow; the results are
// in range by construction and are sliced back to 14 bits.
wire signed [14:0] tri_rise = $signed({1'b0, ph[14:1]}) - 15'sd8192;   // -8192 .. +8191
wire signed [14:0] tri_fall = 15'sd8191 - $signed({1'b0, ph[14:1]});   // +8191 .. -8192
wire signed [14:0] saw_ramp = $signed({1'b0, ph[15:2]}) - 15'sd8192;   // -8192 .. +8191
reg signed [13:0] raw_sine, raw_cos, raw_tri, raw_saw, raw_sq;
wire [LUT_ADDR_W-1:0] sin_addr = ph[15:16-LUT_ADDR_W];
wire [LUT_ADDR_W-1:0] cos_addr = sin_addr + (LUT_DEPTH / 4);   // +90 degrees
// quarter-ROM reads with the fold flags carried alongside (one extra pipeline
// stage for sine/cos relative to the arithmetic waveforms -- harmless, see below)
reg [13:0] s_q, c_q;
reg        s_neg, s_peak, c_neg, c_peak;
initial begin s_q = 14'd0; c_q = 14'd0; end      // defined before the first clock (sim + power-up)
always @(posedge clk) begin                      // ROM reads (no reset: RAM inference)
    s_q <= `WRAP_SIM(#1) sine_rom[qidx(sin_addr)];
    c_q <= `WRAP_SIM(#1) sine_rom[qidx(cos_addr)];
end
always @(posedge clk or negedge rst_n) begin     // fold flags, reset so start-up is defined
    if (!rst_n) begin
        s_neg <= `WRAP_SIM(#1) 1'b0; s_peak <= `WRAP_SIM(#1) 1'b0;
        c_neg <= `WRAP_SIM(#1) 1'b0; c_peak <= `WRAP_SIM(#1) 1'b0;
    end else begin
        s_neg  <= `WRAP_SIM(#1) sin_addr[LUT_ADDR_W-1];
        s_peak <= `WRAP_SIM(#1) sin_addr[LUT_ADDR_W-2] && (sin_addr[QW-1:0] == {QW{1'b0}});
        c_neg  <= `WRAP_SIM(#1) cos_addr[LUT_ADDR_W-1];
        c_peak <= `WRAP_SIM(#1) cos_addr[LUT_ADDR_W-2] && (cos_addr[QW-1:0] == {QW{1'b0}});
    end
end
// fold stage 1: peak insertion (registered), stage 2: negation -- two short
// paths instead of one 14-bit negate behind a mux
reg signed [13:0] s_val, c_val;
reg               s_neg_d, c_neg_d;
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        s_val <= `WRAP_SIM(#1) 14'sd0; c_val <= `WRAP_SIM(#1) 14'sd0;
        s_neg_d <= `WRAP_SIM(#1) 1'b0; c_neg_d <= `WRAP_SIM(#1) 1'b0;
    end else begin
        s_val   <= `WRAP_SIM(#1) s_peak ? 14'sd8191 : $signed(s_q);
        c_val   <= `WRAP_SIM(#1) c_peak ? 14'sd8191 : $signed(c_q);
        s_neg_d <= `WRAP_SIM(#1) s_neg;
        c_neg_d <= `WRAP_SIM(#1) c_neg;
    end
end
always @(posedge clk) begin
    raw_sine <= `WRAP_SIM(#1) s_neg_d ? -s_val : s_val;
    raw_cos  <= `WRAP_SIM(#1) c_neg_d ? -c_val : c_val;
    // triangle: rises -8192..+8191 over the first half, falls over the second
    raw_tri  <= `WRAP_SIM(#1) ph[15] ? tri_fall[13:0] : tri_rise[13:0];
    // sawtooth: -8192 at phase 0 rising to +8191 just before the wrap
    raw_saw  <= `WRAP_SIM(#1) saw_ramp[13:0];
    raw_sq   <= `WRAP_SIM(#1) (ph < duty) ? 14'sd8191 : -14'sd8192;
end

// ---- SSB mixer: two more pipeline stages behind the ROM read; the waveform
// mux below simply picks up raw_ssb two clocks later than the other sources
// (the sources are never mixed, so the skew is irrelevant) ----
reg signed [29:0] p_ic, p_qs;               // Q15 * Q13 = Q28
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        p_ic <= `WRAP_SIM(#1) 30'sd0;
        p_qs <= `WRAP_SIM(#1) 30'sd0;
    end else begin
        p_ic <= `WRAP_SIM(#1) bb_i_d * raw_cos;
        p_qs <= `WRAP_SIM(#1) bb_q_d * raw_sine;
    end
end
reg  signed [30:0] ssb_sum;                 // registered: the 31-bit add/sub alone
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) ssb_sum <= `WRAP_SIM(#1) 31'sd0;
    else        ssb_sum <= `WRAP_SIM(#1) (waveform == `WAVE_SSB_LSB) ? (p_ic + p_qs) : (p_ic - p_qs);
end
wire signed [15:0] ssb_q13 = ssb_sum[30:15];                      // Q28 -> Q13
reg  signed [13:0] raw_ssb;
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) raw_ssb <= `WRAP_SIM(#1) 14'sd0;
    else        raw_ssb <= `WRAP_SIM(#1) (ssb_q13 > 16'sd8191)  ? 14'sd8191 :
                                         (ssb_q13 < -16'sd8192) ? -14'sd8192 : ssb_q13[13:0];
end

// ---- AM: envelope 1 + depth*m in Q15 (32768 = unity), times cos, /2 so 100 %
// modulation peaks at full scale ----
reg [16:0] am_env;                          // 1 .. 65535 (Q15 unsigned)
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) am_env <= `WRAP_SIM(#1) 17'd32768;
    else        am_env <= `WRAP_SIM(#1) 17'd32768 + {mod_prod[32], mod_prod[31:16]};   // + Q31>>16
end
reg signed [31:0] p_am;                     // 18 x 14
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) p_am <= `WRAP_SIM(#1) 32'sd0;
    else        p_am <= `WRAP_SIM(#1) $signed({1'b0, am_env}) * raw_cos;
end
wire signed [15:0] am_q13 = p_am[31:16];    // (Q15 * Q13) >> 16 -> Q13 at half scale
reg  signed [13:0] raw_am;
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) raw_am <= `WRAP_SIM(#1) 14'sd0;
    else        raw_am <= `WRAP_SIM(#1) (am_q13 > 16'sd8191)  ? 14'sd8191 :
                                        (am_q13 < -16'sd8192) ? -14'sd8192 : am_q13[13:0];
end

// ---- stage 3: waveform select ----
reg signed [13:0] raw;
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) raw <= `WRAP_SIM(#1) 14'sd0;
    else case (waveform)
        `WAVE_SINE:     raw <= `WRAP_SIM(#1) raw_sine;
        `WAVE_TRIANGLE: raw <= `WRAP_SIM(#1) raw_tri;
        `WAVE_SAWTOOTH: raw <= `WRAP_SIM(#1) raw_saw;
        `WAVE_SQUARE:   raw <= `WRAP_SIM(#1) raw_sq;
        `WAVE_SSB_USB,
        `WAVE_SSB_LSB:  raw <= `WRAP_SIM(#1) raw_ssb;
        `WAVE_AM:       raw <= `WRAP_SIM(#1) raw_am;
        `WAVE_FM:       raw <= `WRAP_SIM(#1) raw_sine;
        default:             raw <= `WRAP_SIM(#1) 14'sd0;   // WAVE_DC
    endcase
end

// ---- stage 4: amplitude scale: gain = (amplitude + 1) / 65536, so 0xFFFF is exact unity ----
wire        [16:0] gain    = {1'b0, amplitude} + 17'd1;
wire signed [31:0] product = raw * $signed({1'b0, gain});
reg  signed [13:0] scaled;
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) scaled <= `WRAP_SIM(#1) 14'sd0;
    else        scaled <= `WRAP_SIM(#1) product[29:16];
end

// ---- stage 5: DC offset add (registered), then saturation + straight-binary code ----
reg signed [16:0] sum;
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) sum <= `WRAP_SIM(#1) 17'sd0;
    else        sum <= `WRAP_SIM(#1) {{3{scaled[13]}}, scaled} + {offset[15], offset};
end
wire signed [13:0] sat = (sum > 17'sd8191)  ? 14'sd8191 :
                         (sum < -17'sd8192) ? -14'sd8192 : sum[13:0];
wire        [13:0] code = {~sat[13], sat[12:0]};   // +8192: two's complement -> offset binary
always @(posedge clk or negedge rst_n) begin
    if (!rst_n)  dac_code <= `WRAP_SIM(#1) 14'h2000;
    else if (en) dac_code <= `WRAP_SIM(#1) code ^ {14{invert}};
    else         dac_code <= `WRAP_SIM(#1) 14'h2000;
end

endmodule
